//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShoppingForum.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tForum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tForum()
        {
            this.tForumAnalysis = new HashSet<tForumAnalysi>();
            this.tForumReplies = new HashSet<tForumReply>();
            this.tUserFavorites = new HashSet<tUserFavorite>();
        }
    
        public int fPostId { get; set; }
        public int fId { get; set; }
        public string fPostTitle { get; set; }
        public string fPostContent { get; set; }
        public bool fIsPost { get; set; }
        public System.DateTime fCreateTime { get; set; }
        public System.DateTime fUpdateTime { get; set; }
        public bool fEnableFlag { get; set; }
        public Nullable<int> fEnableUserId { get; set; }
        public Nullable<System.DateTime> fDisableTime { get; set; }
        public int fTopSeq { get; set; }
        public int fTotalViewCount { get; set; }
        public int fTotalReplyCount { get; set; }
    
        public virtual tUserProfile tUserProfile { get; set; }
        public virtual tUserProfile tUserProfile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tForumAnalysi> tForumAnalysis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tForumReply> tForumReplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserFavorite> tUserFavorites { get; set; }
    }
}
