//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShoppingForum.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrder()
        {
            this.tOrderDetails = new HashSet<tOrderDetail>();
        }
    
        public int fOrderId { get; set; }
        public int fId { get; set; }
        public System.DateTime fOrderDate { get; set; }
        public Nullable<System.DateTime> fShippedDate { get; set; }
        public Nullable<System.DateTime> fRequiredDate { get; set; }
        public Nullable<int> fScore { get; set; }
        public string fConsigneeName { get; set; }
        public string fConsigneeTelephone { get; set; }
        public string fConsigneeCellPhone { get; set; }
        public string fConsigneeAddress { get; set; }
        public string fOrderCompanyTitle { get; set; }
        public Nullable<int> fOrderTaxIdDNumber { get; set; }
        public string fOrderPostScript { get; set; }
        public string fDiscountCode { get; set; }
        public string fPayment { get; set; }
    
        public virtual tUserProfile tUserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderDetail> tOrderDetails { get; set; }
    }
}
