//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShoppingForum.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tQuestion()
        {
            this.tTests = new HashSet<tTest>();
        }
    
        public int fQuestionId { get; set; }
        public string fQuestionName { get; set; }
        public string fQuestion { get; set; }
        public string fAnswer { get; set; }
        public string fItemA { get; set; }
        public string fItemB { get; set; }
        public string fItemC { get; set; }
        public string fItemD { get; set; }
        public string fItemE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTest> tTests { get; set; }
    }
}
