//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShoppingForum.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTest
    {
        public int fTestId { get; set; }
        public int fId { get; set; }
        public int fQuestionId { get; set; }
        public Nullable<System.DateTime> fTestStar { get; set; }
        public Nullable<System.DateTime> fTestEnd { get; set; }
        public Nullable<System.DateTime> fTestCost { get; set; }
        public Nullable<int> fQuestionCount { get; set; }
        public Nullable<int> fCorrectCount { get; set; }
        public Nullable<System.DateTime> fScoreDate { get; set; }
        public Nullable<int> fQuestionScore { get; set; }
    
        public virtual tQuestion tQuestion { get; set; }
        public virtual tScore tScore { get; set; }
    }
}
